import rainEngineScript from 'virtual:rain-standalone';
import type { RainConfig } from '../../engine/rain';
import { downloadTextFile } from '../../lib/download';

/**
 * Build a fully self-contained screensaver page for the given configuration.
 *
 * `rainEngineScript` is the project's ACTUAL rain engine, bundled to a browser
 * script at build time (see `rainStandalonePlugin` in vite.config.ts) — so the
 * exported file renders with the exact same code the live preview runs, not a
 * reimplementation. The player's chosen config is inlined as a literal and
 * handed straight to `startStandaloneRain()`. No network, no build step, no
 * dependency on the rest of the site: open it in any browser (or point an
 * OS-level "web page as screensaver" tool at it) and it runs full-screen.
 */
export function buildScreensaverHtml(config: RainConfig): string {
  const configJson = JSON.stringify(config);
  const bg = config.backgroundColor;
  const accent = config.color;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="dark" />
<title>OPERATOR // Rain Screensaver</title>
<style>
  html, body { margin: 0; height: 100%; background: ${bg}; overflow: hidden; }
  body { cursor: none; }
  #rain { display: block; width: 100vw; height: 100vh; }
  #hint {
    position: fixed; left: 50%; bottom: 6vh; transform: translateX(-50%);
    font: 12px/1.5 'Share Tech Mono', 'Cascadia Mono', Consolas, monospace;
    letter-spacing: 0.3em; color: ${accent}; text-shadow: 0 0 8px ${accent};
    opacity: 0; pointer-events: none; white-space: nowrap;
    animation: operator-hint 7s ease-out forwards;
  }
  @keyframes operator-hint { 0%, 65% { opacity: 0.55; } 100% { opacity: 0; } }
  @media (prefers-reduced-motion: reduce) { #hint { animation: none; opacity: 0; } }
</style>
</head>
<body>
<canvas id="rain"></canvas>
<div id="hint">// OPERATOR SCREENSAVER &mdash; CLICK TO TOGGLE FULLSCREEN</div>
<script>
(function () {
${rainEngineScript}
  var config = ${configJson};
  var canvas = document.getElementById('rain');
  startStandaloneRain(canvas, config);
  // Convenience when opened as a normal page: click anywhere for fullscreen.
  document.addEventListener('click', function () {
    if (document.fullscreenElement) {
      if (document.exitFullscreen) document.exitFullscreen();
    } else if (document.documentElement.requestFullscreen) {
      document.documentElement.requestFullscreen();
    }
  });
})();
</script>
<!--
  Generated by OPERATOR — an unofficial, non-commercial fan tribute to
  The Matrix trilogy (© Warner Bros., created by the Wachowskis).
  The rain engine above is bundled verbatim from the project's own
  src/engine/rain module. This file is fully standalone: no network, no build.
-->
</body>
</html>
`;
}

/** Generate and download the standalone screensaver for `config`. */
export function downloadScreensaver(config: RainConfig): void {
  downloadTextFile('operator-screensaver.html', buildScreensaverHtml(config), 'text/html;charset=utf-8');
}

/** Approximate exported file size in KB, for the UI's export hint. */
export function estimateSizeKb(config: RainConfig): number {
  return Math.round((buildScreensaverHtml(config).length / 1024) * 10) / 10;
}
